name 'sc-mesosphere'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures sc-mesosphere'
long_description 'Installs/Configures sc-mesosphere'
version '0.1.0'

depends 'zookeeper'
depends 'mesos'
depends 'exhibitor'
depends 'marathon'
depends 'chronos'
depends 'docker'
depends 'haproxy'
depends 'sudo'
